<?php

namespace PayPal\StructType;

use \WsdlToPhp\PackageBase\AbstractStructBase;

/**
 * This class stands for CoupledPaymentInfoType StructType
 * Meta informations extracted from the WSDL
 * - documentation: Information about Coupled Payment transactions.
 * @subpackage Structs
 * @author WsdlToPhp <contact@wsdltophp.com>
 */
class CoupledPaymentInfoType extends AbstractStructBase
{
    /**
     * The CoupledPaymentID
     * Meta informations extracted from the WSDL
     * - documentation: ID that uniquely identifies this CoupledPayment. Generated by PP in Response
     * - maxOccurs: 1
     * - minOccurs: 1
     * @var string
     */
    public $CoupledPaymentID;
    /**
     * The CoupledPaymentRequestID
     * Meta informations extracted from the WSDL
     * - documentation: ID received in the Coupled Payment Request
     * - maxOccurs: 1
     * - minOccurs: 0
     * @var string
     */
    public $CoupledPaymentRequestID;
    /**
     * Constructor method for CoupledPaymentInfoType
     * @uses CoupledPaymentInfoType::setCoupledPaymentID()
     * @uses CoupledPaymentInfoType::setCoupledPaymentRequestID()
     * @param string $coupledPaymentID
     * @param string $coupledPaymentRequestID
     */
    public function __construct($coupledPaymentID = null, $coupledPaymentRequestID = null)
    {
        $this
            ->setCoupledPaymentID($coupledPaymentID)
            ->setCoupledPaymentRequestID($coupledPaymentRequestID);
    }
    /**
     * Get CoupledPaymentID value
     * @return string
     */
    public function getCoupledPaymentID()
    {
        return $this->CoupledPaymentID;
    }
    /**
     * Set CoupledPaymentID value
     * @param string $coupledPaymentID
     * @return \PayPal\StructType\CoupledPaymentInfoType
     */
    public function setCoupledPaymentID($coupledPaymentID = null)
    {
        // validation for constraint: string
        if (!is_null($coupledPaymentID) && !is_string($coupledPaymentID)) {
            throw new \InvalidArgumentException(sprintf('Invalid value, please provide a string, "%s" given', gettype($coupledPaymentID)), __LINE__);
        }
        $this->CoupledPaymentID = $coupledPaymentID;
        return $this;
    }
    /**
     * Get CoupledPaymentRequestID value
     * @return string|null
     */
    public function getCoupledPaymentRequestID()
    {
        return $this->CoupledPaymentRequestID;
    }
    /**
     * Set CoupledPaymentRequestID value
     * @param string $coupledPaymentRequestID
     * @return \PayPal\StructType\CoupledPaymentInfoType
     */
    public function setCoupledPaymentRequestID($coupledPaymentRequestID = null)
    {
        // validation for constraint: string
        if (!is_null($coupledPaymentRequestID) && !is_string($coupledPaymentRequestID)) {
            throw new \InvalidArgumentException(sprintf('Invalid value, please provide a string, "%s" given', gettype($coupledPaymentRequestID)), __LINE__);
        }
        $this->CoupledPaymentRequestID = $coupledPaymentRequestID;
        return $this;
    }
    /**
     * Method called when an object has been exported with var_export() functions
     * It allows to return an object instantiated with the values
     * @see AbstractStructBase::__set_state()
     * @uses AbstractStructBase::__set_state()
     * @param array $array the exported values
     * @return \PayPal\StructType\CoupledPaymentInfoType
     */
    public static function __set_state(array $array)
    {
        return parent::__set_state($array);
    }
    /**
     * Method returning the class name
     * @return string __CLASS__
     */
    public function __toString()
    {
        return __CLASS__;
    }
}
